import type { InterfaceAbi } from 'ethers'
import deployment from './EventTicketing.json'

/**
 * EventTicketing.json is generated by `scripts/deploy.js` in the Hardhat project.
 * Never edit the address by hand — redeploy instead.
 */
export const EVENT_TICKETING_ABI = deployment.abi as InterfaceAbi

export const CONTRACT_ADDRESSES: Record<number, { eventTicketing: string }> = {
  [Number(deployment.chainId)]: { eventTicketing: deployment.address },
}
